"""Second migration

Revision ID: 1f6f260b2079
Revises: 9fbd66f5d0ba
Create Date: 2024-05-19 23:55:49.134018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6f260b2079'
down_revision = '9fbd66f5d0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
